apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2023-11-26T22:07:52Z"
  generation: 9
  labels:
    app: digiskimmer
  name: digiskimmer
  namespace: digiskimmer
  resourceVersion: "3745347"
  uid: 251f9f71-be1e-4c30-b518-6f0f6a42b609
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: digiskimmer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: digiskimmer
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Berlin
        image: lazywalker/digiskr
        imagePullPolicy: Always
        name: digiskr
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/digiskr
          name: settings
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: settings.py
        name: settings
      - emptyDir:
          medium: Memory
          sizeLimit: 256Mi
        name: tmp
